name: Deploy to Remote Server

on:
  push:
    branches:
      - master  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_SECRET_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

      - name: Add EC2 Host Key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ec2-43-204-103-61.ap-south-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Test SSH Connection
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no ubuntu@ec2-43-204-103-61.ap-south-1.compute.amazonaws.com 'echo "SSH Connection Successful"'

      - name: Create Directory on EC2 Instance
        run: |
          ssh -i private_key ubuntu@ec2-43-204-103-61.ap-south-1.compute.amazonaws.com 'sudo bash ~/deploy.sh'
